// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package apideckgo

type Ats struct {
	Applicants   *Applicants
	Applications *Applications
	Jobs         *Jobs

	sdkConfiguration sdkConfiguration
}

func newAts(sdkConfig sdkConfiguration) *Ats {
	return &Ats{
		sdkConfiguration: sdkConfig,
		Applicants:       newApplicants(sdkConfig),
		Applications:     newApplications(sdkConfig),
		Jobs:             newJobs(sdkConfig),
	}
}
