// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"github.com/speakeasy-sdks/apideck-sample-sdk/pkg/utils"
)

// NotFoundResponseDetail2 - Contains parameter or domain specific information related to the error and why it occurred.
type NotFoundResponseDetail2 struct {
}

var _ error = &NotFoundResponseDetail2{}

func (e *NotFoundResponseDetail2) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type NotFoundResponseDetail5Type string

const (
	NotFoundResponseDetail5TypeStr                     NotFoundResponseDetail5Type = "str"
	NotFoundResponseDetail5TypeNotFoundResponseDetail2 NotFoundResponseDetail5Type = "NotFoundResponse_detail_2"
)

type NotFoundResponseDetail5 struct {
	Str                     *string
	NotFoundResponseDetail2 *NotFoundResponseDetail2

	Type NotFoundResponseDetail5Type
}

func CreateNotFoundResponseDetail5Str(str string) NotFoundResponseDetail5 {
	typ := NotFoundResponseDetail5TypeStr

	return NotFoundResponseDetail5{
		Str:  &str,
		Type: typ,
	}
}

func CreateNotFoundResponseDetail5NotFoundResponseDetail2(notFoundResponseDetail2 NotFoundResponseDetail2) NotFoundResponseDetail5 {
	typ := NotFoundResponseDetail5TypeNotFoundResponseDetail2

	return NotFoundResponseDetail5{
		NotFoundResponseDetail2: &notFoundResponseDetail2,
		Type:                    typ,
	}
}

func (u *NotFoundResponseDetail5) UnmarshalJSON(data []byte) error {

	str := new(string)
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = str
		u.Type = NotFoundResponseDetail5TypeStr
		return nil
	}

	notFoundResponseDetail2 := new(NotFoundResponseDetail2)
	if err := utils.UnmarshalJSON(data, &notFoundResponseDetail2, "", true, true); err == nil {
		u.NotFoundResponseDetail2 = notFoundResponseDetail2
		u.Type = NotFoundResponseDetail5TypeNotFoundResponseDetail2
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u NotFoundResponseDetail5) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.NotFoundResponseDetail2 != nil {
		return utils.MarshalJSON(u.NotFoundResponseDetail2, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type NotFoundResponse5 struct {
	// Contains parameter or domain specific information related to the error and why it occurred.
	Detail *NotFoundResponseDetail5 `json:"detail,omitempty"`
	// Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)
	Error_ *string `json:"error,omitempty"`
	// A human-readable message providing more details about the error.
	Message *string `json:"message,omitempty"`
	// Link to documentation of error type
	Ref *string `json:"ref,omitempty"`
	// HTTP status code
	StatusCode *float64 `json:"status_code,omitempty"`
	// The type of error returned
	TypeName *string `json:"type_name,omitempty"`
}

var _ error = &NotFoundResponse5{}

func (e *NotFoundResponse5) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
