// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AddressType - The type of address.
type AddressType string

const (
	AddressTypePrimary   AddressType = "primary"
	AddressTypeSecondary AddressType = "secondary"
	AddressTypeHome      AddressType = "home"
	AddressTypeOffice    AddressType = "office"
	AddressTypeShipping  AddressType = "shipping"
	AddressTypeBilling   AddressType = "billing"
	AddressTypeOther     AddressType = "other"
)

func (e AddressType) ToPointer() *AddressType {
	return &e
}

func (e *AddressType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "secondary":
		fallthrough
	case "home":
		fallthrough
	case "office":
		fallthrough
	case "shipping":
		fallthrough
	case "billing":
		fallthrough
	case "other":
		*e = AddressType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddressType: %v", v)
	}
}

type Address struct {
	// Name of city.
	City *string `json:"city,omitempty"`
	// Name of the contact person at the address
	ContactName *string `json:"contact_name,omitempty"`
	// country code according to ISO 3166-1 alpha-2.
	Country *string `json:"country,omitempty"`
	// Address field that holds a sublocality, such as a county
	County *string `json:"county,omitempty"`
	// Email address of the address
	Email *string `json:"email,omitempty"`
	// Fax number of the address
	Fax *string `json:"fax,omitempty"`
	// Unique identifier for the address.
	ID *string `json:"id,omitempty"`
	// Latitude of the address
	Latitude *string `json:"latitude,omitempty"`
	// Line 1 of the address e.g. number, street, suite, apt #, etc.
	Line1 *string `json:"line1,omitempty"`
	// Line 2 of the address
	Line2 *string `json:"line2,omitempty"`
	// Line 3 of the address
	Line3 *string `json:"line3,omitempty"`
	// Line 4 of the address
	Line4 *string `json:"line4,omitempty"`
	// Longitude of the address
	Longitude *string `json:"longitude,omitempty"`
	// The name of the address.
	Name *string `json:"name,omitempty"`
	// Additional notes
	Notes *string `json:"notes,omitempty"`
	// Phone number of the address
	PhoneNumber *string `json:"phone_number,omitempty"`
	// Zip code or equivalent.
	PostalCode *string `json:"postal_code,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// Salutation of the contact person at the address
	Salutation *string `json:"salutation,omitempty"`
	// Name of state
	State *string `json:"state,omitempty"`
	// Street number
	StreetNumber *string `json:"street_number,omitempty"`
	// The address string. Some APIs don't provide structured address data.
	String *string `json:"string,omitempty"`
	// The type of address.
	Type *AddressType `json:"type,omitempty"`
	// Website of the address
	Website *string `json:"website,omitempty"`
}

func (o *Address) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *Address) GetContactName() *string {
	if o == nil {
		return nil
	}
	return o.ContactName
}

func (o *Address) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *Address) GetCounty() *string {
	if o == nil {
		return nil
	}
	return o.County
}

func (o *Address) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Address) GetFax() *string {
	if o == nil {
		return nil
	}
	return o.Fax
}

func (o *Address) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Address) GetLatitude() *string {
	if o == nil {
		return nil
	}
	return o.Latitude
}

func (o *Address) GetLine1() *string {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *Address) GetLine2() *string {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *Address) GetLine3() *string {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *Address) GetLine4() *string {
	if o == nil {
		return nil
	}
	return o.Line4
}

func (o *Address) GetLongitude() *string {
	if o == nil {
		return nil
	}
	return o.Longitude
}

func (o *Address) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Address) GetNotes() *string {
	if o == nil {
		return nil
	}
	return o.Notes
}

func (o *Address) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *Address) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *Address) GetRowVersion() *string {
	if o == nil {
		return nil
	}
	return o.RowVersion
}

func (o *Address) GetSalutation() *string {
	if o == nil {
		return nil
	}
	return o.Salutation
}

func (o *Address) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *Address) GetStreetNumber() *string {
	if o == nil {
		return nil
	}
	return o.StreetNumber
}

func (o *Address) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}

func (o *Address) GetType() *AddressType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Address) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}
