// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ApplicantsFilter struct {
	// Id of the job to filter on
	JobID *string `queryParam:"name=job_id"`
}

func (o *ApplicantsFilter) GetJobID() *string {
	if o == nil {
		return nil
	}
	return o.JobID
}
