// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateApplicationResponse struct {
	Data UnifiedID `json:"data"`
	// Operation performed
	Operation string `json:"operation"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// HTTP Response Status
	Status string `json:"status"`
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
}

func (o *CreateApplicationResponse) GetData() UnifiedID {
	if o == nil {
		return UnifiedID{}
	}
	return o.Data
}

func (o *CreateApplicationResponse) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

func (o *CreateApplicationResponse) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *CreateApplicationResponse) GetService() string {
	if o == nil {
		return ""
	}
	return o.Service
}

func (o *CreateApplicationResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *CreateApplicationResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}
