// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Currency - Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
type Currency string

const (
	CurrencyUnknownCurrency Currency = "UNKNOWN_CURRENCY"
	CurrencyAed             Currency = "AED"
	CurrencyAfn             Currency = "AFN"
	CurrencyAll             Currency = "ALL"
	CurrencyAmd             Currency = "AMD"
	CurrencyAng             Currency = "ANG"
	CurrencyAoa             Currency = "AOA"
	CurrencyArs             Currency = "ARS"
	CurrencyAud             Currency = "AUD"
	CurrencyAwg             Currency = "AWG"
	CurrencyAzn             Currency = "AZN"
	CurrencyBam             Currency = "BAM"
	CurrencyBbd             Currency = "BBD"
	CurrencyBdt             Currency = "BDT"
	CurrencyBgn             Currency = "BGN"
	CurrencyBhd             Currency = "BHD"
	CurrencyBif             Currency = "BIF"
	CurrencyBmd             Currency = "BMD"
	CurrencyBnd             Currency = "BND"
	CurrencyBob             Currency = "BOB"
	CurrencyBov             Currency = "BOV"
	CurrencyBrl             Currency = "BRL"
	CurrencyBsd             Currency = "BSD"
	CurrencyBtn             Currency = "BTN"
	CurrencyBwp             Currency = "BWP"
	CurrencyByr             Currency = "BYR"
	CurrencyBzd             Currency = "BZD"
	CurrencyCad             Currency = "CAD"
	CurrencyCdf             Currency = "CDF"
	CurrencyChe             Currency = "CHE"
	CurrencyChf             Currency = "CHF"
	CurrencyChw             Currency = "CHW"
	CurrencyClf             Currency = "CLF"
	CurrencyClp             Currency = "CLP"
	CurrencyCny             Currency = "CNY"
	CurrencyCop             Currency = "COP"
	CurrencyCou             Currency = "COU"
	CurrencyCrc             Currency = "CRC"
	CurrencyCuc             Currency = "CUC"
	CurrencyCup             Currency = "CUP"
	CurrencyCve             Currency = "CVE"
	CurrencyCzk             Currency = "CZK"
	CurrencyDjf             Currency = "DJF"
	CurrencyDkk             Currency = "DKK"
	CurrencyDop             Currency = "DOP"
	CurrencyDzd             Currency = "DZD"
	CurrencyEgp             Currency = "EGP"
	CurrencyErn             Currency = "ERN"
	CurrencyEtb             Currency = "ETB"
	CurrencyEur             Currency = "EUR"
	CurrencyFjd             Currency = "FJD"
	CurrencyFkp             Currency = "FKP"
	CurrencyGbp             Currency = "GBP"
	CurrencyGel             Currency = "GEL"
	CurrencyGhs             Currency = "GHS"
	CurrencyGip             Currency = "GIP"
	CurrencyGmd             Currency = "GMD"
	CurrencyGnf             Currency = "GNF"
	CurrencyGtq             Currency = "GTQ"
	CurrencyGyd             Currency = "GYD"
	CurrencyHkd             Currency = "HKD"
	CurrencyHnl             Currency = "HNL"
	CurrencyHrk             Currency = "HRK"
	CurrencyHtg             Currency = "HTG"
	CurrencyHuf             Currency = "HUF"
	CurrencyIdr             Currency = "IDR"
	CurrencyIls             Currency = "ILS"
	CurrencyInr             Currency = "INR"
	CurrencyIqd             Currency = "IQD"
	CurrencyIrr             Currency = "IRR"
	CurrencyIsk             Currency = "ISK"
	CurrencyJmd             Currency = "JMD"
	CurrencyJod             Currency = "JOD"
	CurrencyJpy             Currency = "JPY"
	CurrencyKes             Currency = "KES"
	CurrencyKgs             Currency = "KGS"
	CurrencyKhr             Currency = "KHR"
	CurrencyKmf             Currency = "KMF"
	CurrencyKpw             Currency = "KPW"
	CurrencyKrw             Currency = "KRW"
	CurrencyKwd             Currency = "KWD"
	CurrencyKyd             Currency = "KYD"
	CurrencyKzt             Currency = "KZT"
	CurrencyLak             Currency = "LAK"
	CurrencyLbp             Currency = "LBP"
	CurrencyLkr             Currency = "LKR"
	CurrencyLrd             Currency = "LRD"
	CurrencyLsl             Currency = "LSL"
	CurrencyLtl             Currency = "LTL"
	CurrencyLvl             Currency = "LVL"
	CurrencyLyd             Currency = "LYD"
	CurrencyMad             Currency = "MAD"
	CurrencyMdl             Currency = "MDL"
	CurrencyMga             Currency = "MGA"
	CurrencyMkd             Currency = "MKD"
	CurrencyMmk             Currency = "MMK"
	CurrencyMnt             Currency = "MNT"
	CurrencyMop             Currency = "MOP"
	CurrencyMro             Currency = "MRO"
	CurrencyMur             Currency = "MUR"
	CurrencyMvr             Currency = "MVR"
	CurrencyMwk             Currency = "MWK"
	CurrencyMxn             Currency = "MXN"
	CurrencyMxv             Currency = "MXV"
	CurrencyMyr             Currency = "MYR"
	CurrencyMzn             Currency = "MZN"
	CurrencyNad             Currency = "NAD"
	CurrencyNgn             Currency = "NGN"
	CurrencyNio             Currency = "NIO"
	CurrencyNok             Currency = "NOK"
	CurrencyNpr             Currency = "NPR"
	CurrencyNzd             Currency = "NZD"
	CurrencyOmr             Currency = "OMR"
	CurrencyPab             Currency = "PAB"
	CurrencyPen             Currency = "PEN"
	CurrencyPgk             Currency = "PGK"
	CurrencyPhp             Currency = "PHP"
	CurrencyPkr             Currency = "PKR"
	CurrencyPln             Currency = "PLN"
	CurrencyPyg             Currency = "PYG"
	CurrencyQar             Currency = "QAR"
	CurrencyRon             Currency = "RON"
	CurrencyRsd             Currency = "RSD"
	CurrencyRub             Currency = "RUB"
	CurrencyRwf             Currency = "RWF"
	CurrencySar             Currency = "SAR"
	CurrencySbd             Currency = "SBD"
	CurrencyScr             Currency = "SCR"
	CurrencySdg             Currency = "SDG"
	CurrencySek             Currency = "SEK"
	CurrencySgd             Currency = "SGD"
	CurrencyShp             Currency = "SHP"
	CurrencySll             Currency = "SLL"
	CurrencySos             Currency = "SOS"
	CurrencySrd             Currency = "SRD"
	CurrencySsp             Currency = "SSP"
	CurrencyStd             Currency = "STD"
	CurrencySvc             Currency = "SVC"
	CurrencySyp             Currency = "SYP"
	CurrencySzl             Currency = "SZL"
	CurrencyThb             Currency = "THB"
	CurrencyTjs             Currency = "TJS"
	CurrencyTmt             Currency = "TMT"
	CurrencyTnd             Currency = "TND"
	CurrencyTop             Currency = "TOP"
	CurrencyTrc             Currency = "TRC"
	CurrencyTry             Currency = "TRY"
	CurrencyTtd             Currency = "TTD"
	CurrencyTwd             Currency = "TWD"
	CurrencyTzs             Currency = "TZS"
	CurrencyUah             Currency = "UAH"
	CurrencyUgx             Currency = "UGX"
	CurrencyUsd             Currency = "USD"
	CurrencyUsn             Currency = "USN"
	CurrencyUss             Currency = "USS"
	CurrencyUyi             Currency = "UYI"
	CurrencyUyu             Currency = "UYU"
	CurrencyUzs             Currency = "UZS"
	CurrencyVef             Currency = "VEF"
	CurrencyVnd             Currency = "VND"
	CurrencyVuv             Currency = "VUV"
	CurrencyWst             Currency = "WST"
	CurrencyXaf             Currency = "XAF"
	CurrencyXag             Currency = "XAG"
	CurrencyXau             Currency = "XAU"
	CurrencyXba             Currency = "XBA"
	CurrencyXbb             Currency = "XBB"
	CurrencyXbc             Currency = "XBC"
	CurrencyXbd             Currency = "XBD"
	CurrencyXcd             Currency = "XCD"
	CurrencyXdr             Currency = "XDR"
	CurrencyXof             Currency = "XOF"
	CurrencyXpd             Currency = "XPD"
	CurrencyXpf             Currency = "XPF"
	CurrencyXpt             Currency = "XPT"
	CurrencyXts             Currency = "XTS"
	CurrencyXxx             Currency = "XXX"
	CurrencyYer             Currency = "YER"
	CurrencyZar             Currency = "ZAR"
	CurrencyZmk             Currency = "ZMK"
	CurrencyZmw             Currency = "ZMW"
	CurrencyBtc             Currency = "BTC"
	CurrencyEth             Currency = "ETH"
)

func (e Currency) ToPointer() *Currency {
	return &e
}

func (e *Currency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN_CURRENCY":
		fallthrough
	case "AED":
		fallthrough
	case "AFN":
		fallthrough
	case "ALL":
		fallthrough
	case "AMD":
		fallthrough
	case "ANG":
		fallthrough
	case "AOA":
		fallthrough
	case "ARS":
		fallthrough
	case "AUD":
		fallthrough
	case "AWG":
		fallthrough
	case "AZN":
		fallthrough
	case "BAM":
		fallthrough
	case "BBD":
		fallthrough
	case "BDT":
		fallthrough
	case "BGN":
		fallthrough
	case "BHD":
		fallthrough
	case "BIF":
		fallthrough
	case "BMD":
		fallthrough
	case "BND":
		fallthrough
	case "BOB":
		fallthrough
	case "BOV":
		fallthrough
	case "BRL":
		fallthrough
	case "BSD":
		fallthrough
	case "BTN":
		fallthrough
	case "BWP":
		fallthrough
	case "BYR":
		fallthrough
	case "BZD":
		fallthrough
	case "CAD":
		fallthrough
	case "CDF":
		fallthrough
	case "CHE":
		fallthrough
	case "CHF":
		fallthrough
	case "CHW":
		fallthrough
	case "CLF":
		fallthrough
	case "CLP":
		fallthrough
	case "CNY":
		fallthrough
	case "COP":
		fallthrough
	case "COU":
		fallthrough
	case "CRC":
		fallthrough
	case "CUC":
		fallthrough
	case "CUP":
		fallthrough
	case "CVE":
		fallthrough
	case "CZK":
		fallthrough
	case "DJF":
		fallthrough
	case "DKK":
		fallthrough
	case "DOP":
		fallthrough
	case "DZD":
		fallthrough
	case "EGP":
		fallthrough
	case "ERN":
		fallthrough
	case "ETB":
		fallthrough
	case "EUR":
		fallthrough
	case "FJD":
		fallthrough
	case "FKP":
		fallthrough
	case "GBP":
		fallthrough
	case "GEL":
		fallthrough
	case "GHS":
		fallthrough
	case "GIP":
		fallthrough
	case "GMD":
		fallthrough
	case "GNF":
		fallthrough
	case "GTQ":
		fallthrough
	case "GYD":
		fallthrough
	case "HKD":
		fallthrough
	case "HNL":
		fallthrough
	case "HRK":
		fallthrough
	case "HTG":
		fallthrough
	case "HUF":
		fallthrough
	case "IDR":
		fallthrough
	case "ILS":
		fallthrough
	case "INR":
		fallthrough
	case "IQD":
		fallthrough
	case "IRR":
		fallthrough
	case "ISK":
		fallthrough
	case "JMD":
		fallthrough
	case "JOD":
		fallthrough
	case "JPY":
		fallthrough
	case "KES":
		fallthrough
	case "KGS":
		fallthrough
	case "KHR":
		fallthrough
	case "KMF":
		fallthrough
	case "KPW":
		fallthrough
	case "KRW":
		fallthrough
	case "KWD":
		fallthrough
	case "KYD":
		fallthrough
	case "KZT":
		fallthrough
	case "LAK":
		fallthrough
	case "LBP":
		fallthrough
	case "LKR":
		fallthrough
	case "LRD":
		fallthrough
	case "LSL":
		fallthrough
	case "LTL":
		fallthrough
	case "LVL":
		fallthrough
	case "LYD":
		fallthrough
	case "MAD":
		fallthrough
	case "MDL":
		fallthrough
	case "MGA":
		fallthrough
	case "MKD":
		fallthrough
	case "MMK":
		fallthrough
	case "MNT":
		fallthrough
	case "MOP":
		fallthrough
	case "MRO":
		fallthrough
	case "MUR":
		fallthrough
	case "MVR":
		fallthrough
	case "MWK":
		fallthrough
	case "MXN":
		fallthrough
	case "MXV":
		fallthrough
	case "MYR":
		fallthrough
	case "MZN":
		fallthrough
	case "NAD":
		fallthrough
	case "NGN":
		fallthrough
	case "NIO":
		fallthrough
	case "NOK":
		fallthrough
	case "NPR":
		fallthrough
	case "NZD":
		fallthrough
	case "OMR":
		fallthrough
	case "PAB":
		fallthrough
	case "PEN":
		fallthrough
	case "PGK":
		fallthrough
	case "PHP":
		fallthrough
	case "PKR":
		fallthrough
	case "PLN":
		fallthrough
	case "PYG":
		fallthrough
	case "QAR":
		fallthrough
	case "RON":
		fallthrough
	case "RSD":
		fallthrough
	case "RUB":
		fallthrough
	case "RWF":
		fallthrough
	case "SAR":
		fallthrough
	case "SBD":
		fallthrough
	case "SCR":
		fallthrough
	case "SDG":
		fallthrough
	case "SEK":
		fallthrough
	case "SGD":
		fallthrough
	case "SHP":
		fallthrough
	case "SLL":
		fallthrough
	case "SOS":
		fallthrough
	case "SRD":
		fallthrough
	case "SSP":
		fallthrough
	case "STD":
		fallthrough
	case "SVC":
		fallthrough
	case "SYP":
		fallthrough
	case "SZL":
		fallthrough
	case "THB":
		fallthrough
	case "TJS":
		fallthrough
	case "TMT":
		fallthrough
	case "TND":
		fallthrough
	case "TOP":
		fallthrough
	case "TRC":
		fallthrough
	case "TRY":
		fallthrough
	case "TTD":
		fallthrough
	case "TWD":
		fallthrough
	case "TZS":
		fallthrough
	case "UAH":
		fallthrough
	case "UGX":
		fallthrough
	case "USD":
		fallthrough
	case "USN":
		fallthrough
	case "USS":
		fallthrough
	case "UYI":
		fallthrough
	case "UYU":
		fallthrough
	case "UZS":
		fallthrough
	case "VEF":
		fallthrough
	case "VND":
		fallthrough
	case "VUV":
		fallthrough
	case "WST":
		fallthrough
	case "XAF":
		fallthrough
	case "XAG":
		fallthrough
	case "XAU":
		fallthrough
	case "XBA":
		fallthrough
	case "XBB":
		fallthrough
	case "XBC":
		fallthrough
	case "XBD":
		fallthrough
	case "XCD":
		fallthrough
	case "XDR":
		fallthrough
	case "XOF":
		fallthrough
	case "XPD":
		fallthrough
	case "XPF":
		fallthrough
	case "XPT":
		fallthrough
	case "XTS":
		fallthrough
	case "XXX":
		fallthrough
	case "YER":
		fallthrough
	case "ZAR":
		fallthrough
	case "ZMK":
		fallthrough
	case "ZMW":
		fallthrough
	case "BTC":
		fallthrough
	case "ETH":
		*e = Currency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Currency: %v", v)
	}
}
