// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/apideck-go/pkg/utils"
)

type Four struct {
}

type ValueType string

const (
	ValueTypeStr        ValueType = "str"
	ValueTypeNumber     ValueType = "number"
	ValueTypeBoolean    ValueType = "boolean"
	ValueTypeFour       ValueType = "4"
	ValueTypeArrayOfstr ValueType = "arrayOfstr"
)

type Value struct {
	Str        *string
	Number     *float64
	Boolean    *bool
	Four       *Four
	ArrayOfstr []string

	Type ValueType
}

func CreateValueStr(str string) Value {
	typ := ValueTypeStr

	return Value{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueNumber(number float64) Value {
	typ := ValueTypeNumber

	return Value{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueBoolean(boolean bool) Value {
	typ := ValueTypeBoolean

	return Value{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValueFour(four Four) Value {
	typ := ValueTypeFour

	return Value{
		Four: &four,
		Type: typ,
	}
}

func CreateValueArrayOfstr(arrayOfstr []string) Value {
	typ := ValueTypeArrayOfstr

	return Value{
		ArrayOfstr: arrayOfstr,
		Type:       typ,
	}
}

func (u *Value) UnmarshalJSON(data []byte) error {

	four := Four{}
	if err := utils.UnmarshalJSON(data, &four, "", true, true); err == nil {
		u.Four = &four
		u.Type = ValueTypeFour
		return nil
	}

	str := ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = ValueTypeStr
		return nil
	}

	number := float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, true); err == nil {
		u.Number = &number
		u.Type = ValueTypeNumber
		return nil
	}

	boolean := false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = &boolean
		u.Type = ValueTypeBoolean
		return nil
	}

	arrayOfstr := []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfstr, "", true, true); err == nil {
		u.ArrayOfstr = arrayOfstr
		u.Type = ValueTypeArrayOfstr
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u Value) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.Four != nil {
		return utils.MarshalJSON(u.Four, "", true)
	}

	if u.ArrayOfstr != nil {
		return utils.MarshalJSON(u.ArrayOfstr, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type CustomField struct {
	// More information about the custom field
	Description *string `json:"description,omitempty"`
	// Unique identifier for the custom field.
	ID *string `json:"id"`
	// Name of the custom field.
	Name  *string `json:"name,omitempty"`
	Value *Value  `json:"value,omitempty"`
}

func (o *CustomField) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CustomField) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CustomField) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CustomField) GetValue() *Value {
	if o == nil {
		return nil
	}
	return o.Value
}
