// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetApplicantResponse struct {
	Data Applicant `json:"data"`
	// Operation performed
	Operation string `json:"operation"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// HTTP Response Status
	Status string `json:"status"`
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
}

func (o *GetApplicantResponse) GetData() Applicant {
	if o == nil {
		return Applicant{}
	}
	return o.Data
}

func (o *GetApplicantResponse) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

func (o *GetApplicantResponse) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *GetApplicantResponse) GetService() string {
	if o == nil {
		return ""
	}
	return o.Service
}

func (o *GetApplicantResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetApplicantResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}
