// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetApplicationResponse struct {
	Data Application `json:"data"`
	// Operation performed
	Operation string `json:"operation"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// HTTP Response Status
	Status string `json:"status"`
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
}

func (o *GetApplicationResponse) GetData() Application {
	if o == nil {
		return Application{}
	}
	return o.Data
}

func (o *GetApplicationResponse) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

func (o *GetApplicationResponse) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *GetApplicationResponse) GetService() string {
	if o == nil {
		return ""
	}
	return o.Service
}

func (o *GetApplicationResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetApplicationResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}
