// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetApplicationsResponse struct {
	Data []Application `json:"data"`
	// Links to navigate to previous or next pages through the API
	Links *Links `json:"links,omitempty"`
	// Response metadata
	Meta *Meta `json:"meta,omitempty"`
	// Operation performed
	Operation string `json:"operation"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// HTTP Response Status
	Status string `json:"status"`
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
}

func (o *GetApplicationsResponse) GetData() []Application {
	if o == nil {
		return []Application{}
	}
	return o.Data
}

func (o *GetApplicationsResponse) GetLinks() *Links {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *GetApplicationsResponse) GetMeta() *Meta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *GetApplicationsResponse) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

func (o *GetApplicationsResponse) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *GetApplicationsResponse) GetService() string {
	if o == nil {
		return ""
	}
	return o.Service
}

func (o *GetApplicationsResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetApplicationsResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}
