// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// JobStatus - The status of the job.
type JobStatus string

const (
	JobStatusDraft     JobStatus = "draft"
	JobStatusInternal  JobStatus = "internal"
	JobStatusPublished JobStatus = "published"
	JobStatusCompleted JobStatus = "completed"
	JobStatusOnHold    JobStatus = "on-hold"
	JobStatusPrivate   JobStatus = "private"
)

func (e JobStatus) ToPointer() *JobStatus {
	return &e
}

func (e *JobStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "internal":
		fallthrough
	case "published":
		fallthrough
	case "completed":
		fallthrough
	case "on-hold":
		fallthrough
	case "private":
		*e = JobStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobStatus: %v", v)
	}
}
