// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Links to navigate to previous or next pages through the API
type Links struct {
	// Link to navigate to the current page through the API
	Current *string `json:"current,omitempty"`
	// Link to navigate to the previous page through the API
	Next *string `json:"next,omitempty"`
	// Link to navigate to the previous page through the API
	Previous *string `json:"previous,omitempty"`
}

func (o *Links) GetCurrent() *string {
	if o == nil {
		return nil
	}
	return o.Current
}

func (o *Links) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *Links) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}
