// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UnifiedID struct {
	// The unique identifier of the resource
	ID string `json:"id"`
}

func (o *UnifiedID) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
